// src/types/job.d.ts

// Renamed to avoid conflict, this is your frontend Job type
export interface Job {
    id: string; // UUID from Supabase
    title: string;
    company: string;
    location: string;
    salary: string; // Combined string: "USD 15000 - 20000"
    type: 'full-time' | 'part-time' | 'contract' | 'internship'; // Added 'internship'
    status: 'active' | 'inactive' | 'draft'; // Frontend specific statuses
    applicants: number;
    createdAt: string; // Mapped from posted_time
    description: string;
    requirements: string[]; // Mapped from responsibilities
    skills: string[];
    category: 'hospitality' | 'logistics' | 'construction' | 'travel' | 'tourism' | 'service';
    experience_level: string; // Assuming you'll add this to the form later if needed
    tags: string[]; // Assuming tags are used
  }
  
  // Type for data fetched from Supabase (snake_case from DB)
  export interface SupabaseJobData {
    id: string; // UUID from Supabase
    created_at: string; // Auto-generated by Supabase but good to have
    title: string;
    company: string;
    location: string;
    job_type: string;
    min_salary: number | null;
    max_salary: number | null;
    currency: string;
    posted_time: string; // Typically timestamp with timezone from DB
    tags: string[]; // Assuming Supabase stores these as text[] or JSONB
    category: string;
    experience_level: string;
    description: string;
    responsibilities: string[]; // Assuming Supabase stores these as text[] or JSONB
    skills: string[]; // Assuming Supabase stores these as text[] or JSONB
    status: 'active' | 'inactive' | 'pause'; // Added 'pause' as per discussion
    applicants: number; // Assuming applicants count is stored directly in DB
  }
  
  // Type for data to be inserted or updated into Supabase (matches DB schema directly)
  // We make all fields optional for updates as you might only send changed fields.
  // For insert, the handleCreateJob will ensure required fields are present.
  export interface JobUpsertData {
    title?: string;
    company?: string;
    location?: string;
    job_type?: string;
    min_salary?: number | null;
    max_salary?: number | null;
    currency?: string;
    posted_time?: string;
    tags?: string[];
    category?: string;
    experience_level?: string;
    description?: string;
    responsibilities?: string[];
    skills?: string[];
    status?: 'active' | 'inactive' | 'pause';
    applicants?: number;
  }